// ─── Currency ────────────────────────────────────────────────────────────────

export function formatUGX(amount: number): string {
  return new Intl.NumberFormat("en-UG", {
    style: "currency",
    currency: "UGX",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

// ─── Tax ─────────────────────────────────────────────────────────────────────

/** Rental income withholding tax rate for individuals (URA) */
export const WITHHOLDING_TAX_RATE = 0.06;

export function calcWithholdingTax(grossRent: number): number {
  return grossRent * WITHHOLDING_TAX_RATE;
}

// ─── Districts ────────────────────────────────────────────────────────────────

export const UGANDA_DISTRICTS = [
  "Abim",
  "Adjumani",
  "Agago",
  "Alebtong",
  "Amolatar",
  "Amudat",
  "Amuria",
  "Amuru",
  "Apac",
  "Arua",
  "Budaka",
  "Bududa",
  "Bugiri",
  "Bugweri",
  "Buhweju",
  "Buikwe",
  "Bukedea",
  "Bukomansimbi",
  "Bukwo",
  "Bulambuli",
  "Buliisa",
  "Bundibugyo",
  "Bunyangabu",
  "Bushenyi",
  "Busia",
  "Butaleja",
  "Butebo",
  "Buvuma",
  "Buyende",
  "Dokolo",
  "Gomba",
  "Gulu",
  "Hoima",
  "Ibanda",
  "Iganga",
  "Isingiro",
  "Jinja",
  "Kaabong",
  "Kabale",
  "Kabarole",
  "Kaberamaido",
  "Kagadi",
  "Kakumiro",
  "Kalaki",
  "Kalangala",
  "Kaliro",
  "Kalungu",
  "Kampala",
  "Kamuli",
  "Kamwenge",
  "Kanungu",
  "Kapchorwa",
  "Kapelebyong",
  "Karenga",
  "Kasanda",
  "Kasese",
  "Katakwi",
  "Kayunga",
  "Kazo",
  "Kibaale",
  "Kiboga",
  "Kibuku",
  "Kikuube",
  "Kiruhura",
  "Kiryandongo",
  "Kisoro",
  "Kitagwenda",
  "Kitgum",
  "Koboko",
  "Kole",
  "Kotido",
  "Kumi",
  "Kwania",
  "Kween",
  "Kyankwanzi",
  "Kyegegwa",
  "Kyenjojo",
  "Kyotera",
  "Lamwo",
  "Lira",
  "Luuka",
  "Luwero",
  "Lwengo",
  "Lyantonde",
  "Madi-Okollo",
  "Manafwa",
  "Maracha",
  "Masaka",
  "Masindi",
  "Mayuge",
  "Mbale",
  "Mbarara",
  "Mitooma",
  "Mityana",
  "Moroto",
  "Moyo",
  "Mpigi",
  "Mubende",
  "Mukono",
  "Nabilatuk",
  "Nakapiripirit",
  "Nakaseke",
  "Nakasongola",
  "Namayingo",
  "Namisindwa",
  "Namutumba",
  "Napak",
  "Nebbi",
  "Ngora",
  "Ntoroko",
  "Ntungamo",
  "Nwoya",
  "Obongi",
  "Omoro",
  "Otuke",
  "Oyam",
  "Pader",
  "Pakwach",
  "Pallisa",
  "Rakai",
  "Rubanda",
  "Rubirizi",
  "Rukiga",
  "Rukungiri",
  "Rwampara",
  "Sembabule",
  "Serere",
  "Sheema",
  "Sironko",
  "Soroti",
  "Tororo",
  "Wakiso",
  "Yumbe",
  "Zombo",
] as const;

export type UgandaDistrict = (typeof UGANDA_DISTRICTS)[number];